### ISSUE TITLE
Event Listener Not Removed - Memory Leak

### ISSUE THREAD

**Issue by mstachowiak** [rsdavis/svelte-collapse#5]
The event listener for transitionend is not removed, resulting in a memory leak.

In the code:
```
const listener = node.addEventListener('transitionend', () => {
    transitionEndResolve();
    transitionEndResolve = noop;
    transitionEndReject = noop;
});
```

The listener variable is assigned the result of node.addEventListener(...), but addEventListener returns void, not the listener function.

When you later try to remove the listener using removeEventListener('transitionend', listener), you're effectively passing undefined or void to removeEventListener, which does not correspond to the actual listener function that was registered. As a result, the listener is not removed.

To correctly remove an event listener, you need to pass the exact function reference that was originally registered. 
```
// Define the listener function separately
const listener = () => {
    transitionEndResolve();
    transitionEndResolve = noop;
    transitionEndReject = noop;
};

// Add the listener
node.addEventListener('transitionend', listener);

// Later, remove the listener correctly
function destroy() {
    node.removeEventListener('transitionend', listener);
}
```

**Comment by rsdavis** [comment]
Merged changes, bumbed the version, and deployed to npm 
https://www.npmjs.com/package/svelte-collapse/v/0.1.3
Thanks!

**Comment by mstachowiak** [comment]
Awesome, thanks for the quick turnaround!  Appreciate the library, serving us well in our product.
